spring:
  profiles: local
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: false
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
  servlet:
    context-path: '/v1/admin'


